<?php

namespace Stage\AdminBundle\Repository;

/**
 * FederationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FederationRepository extends \Doctrine\ORM\EntityRepository
{

    public function countAll()
    {

        return $this->getEntityManager()
            ->createQuery('SELECT count(a) FROM StageAdminBundle:Federation a')
            ->getSingleScalarResult() ;
    }



}
