<?php

namespace Stage\AdminBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {

        return $this->getEntityManager()
            ->createQuery('SELECT count(a) FROM StageAdminBundle:Joueur a')
            ->getSingleScalarResult() ;
    }
}
